### ISSUE TITLE
Updating/work-with this template for GHA feature

### ISSUE THREAD

**Issue by v-jiaodi** [jsburckhardt/docusaurus-aca#8]
We are updating this template to support new features in `Github Action`.

**For the Github Action feature**: We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
![image](https://github.com/jsburckhardt/docusaurus-aca/assets/80496810/11ce8d77-333a-433b-8437-29325f1e72fb)

@rajeshkamal5050 , @jsburckhardt  for notification.

**Comment by jsburckhardt** [comment]
#10 closes
